spring:
  application:
    name: thinking-cloud-starter-gateway
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
logging:
  level:
    com.netflix: DEBUG
server:
  port: 8770
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}::${eureka.instance.hostname}::${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    healthcheck:
      enabled: true
ribbon:
  eager-load:
    enabled: true
zuul:
  add-host-header: true
  force-original-query-string-encoding: true
  host:
    connect-timeout-millis: 1800000
    socket-timeout-millis: 1800000
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 1000
  sensitive-headers: Content-Type:application/json
#  thread-pool:
#    use-separate-thread-pools: true
---
spring:
  profiles: dev
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5