spring:
  application:
    name: logistics-service-upgrade
  aop:
    proxy-target-class: true
  cloud:
    client:
      ip:
        address: localhost
    inetutils:
      use-only-site-local-interfaces: true
#  data:
#    rest:
#      base-path: upgrade
  datasource:
    # JDBC 配置
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@10.71.0.30:1521:LMISHLJ
    username: lmis
    password: lmishljnet
    druid:
#      oracle: true
      # 连接池配置
      name: druidPool
      default-auto-commit: false
      default-transaction-isolation: 2
      share-prepared-statements: true
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 2000
      pool-prepared-statements: true
#      max-open-prepared-statements: 512
      max-pool-prepared-statement-per-connection-size: 512
      validation-query: select 1 from dual
      validation-query-timeout: 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 7200000
      remove-abandoned-timeout: 1800
      filters: stat,log4j,wall
      # 监控配置
      web-stat-filter:
        exclusions: /public/*,*.js,*.css,/druid*,*.jsp,*.swf
      stat-view-servlet:
        login-username: druid
        login-password: druid
      aop-patterns: org.thinking.logistics.service.*
      use-oracle-implicit-cache: true
      access-to-underlying-connection-allowed: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    type: oracle.jdbc.pool.OracleDataSource
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.3.87.203:1521:LMISHLJ
#    username: lmis
#    password: lmishljnet
#    initialize: false
#    hikari:
#      pool-name: hikari-pool-resource
##      driver-class-name: oracle.jdbc.OracleDriver
#      jdbc-url: jdbc:oracle:thin:@10.3.87.203:1521:LMISHLJ
#      username: LMIS
#      password: lmishljnet
#      auto-commit: false
##      connection-timeout: 7200000
#      login-timeout: 10000
#      maximum-pool-size: 30
#      leak-detection-threshold: 10000
##      max-lifetime: 7200000
##      minimum-idle: 1800000
  jpa:
    database: oracle
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
security:
  basic:
    enabled: false
  user:
    name: henry
    password: ocp9i_Explorer
server:
  port: 8780
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}::${eureka.instance.hostname}::${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
    healthcheck:
      enabled: true
---
spring:
  profiles: dev
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5