spring:
  application:
    name: thinking-cloud-starter-eureka-server
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    instance-id: ${spring.application.name}::${eureka.instance.hostname}::${server.port}
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka
    healthcheck:
      enabled: true
  environment: product-peer1
  datacenter: cloud-peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    instance-id: ${spring.application.name}::${eureka.instance.hostname}::${server.port}
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka
    healthcheck:
      enabled: true
  environment: product-peer2
  datacenter: cloud-peer2