spring:
  application:
    name: thinking-cloud-starter-hystrix-turbine
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
server:
  port: 8782
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}::${eureka.instance.hostname}::${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
    healthcheck:
      enabled: true
turbine:
  app-config: logistics-service-common,logistics-service-inventory
  cluster-name-expression: "'default'"