spring:
  application:
    name: data-exchange
  aop:
    proxy-target-class: true
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
  datasource:
    # JDBC 配置
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@10.211.55.3:1521:WMS
    username: exwms
    password: exwms
#    url: jdbc:mysql://10.3.87.202:3306/jlp
#    username: wf
#    password: wf
    druid:
      # 连接池配置
      name: druidPool
      default-auto-commit: false
      share-prepared-statements: true
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 2000
      pool-prepared-statements: true
#      max-open-prepared-statements: 512
      max-pool-prepared-statement-per-connection-size: 512
      validation-query: select 1 from dual
      validation-query-timeout: 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 7200000
      remove-abandoned-timeout: 1800
#      filters: stat,log4j,wall
      # 监控配置
      web-stat-filter:
        exclusions: /public/*,*.js,*.css,/druid*,*.jsp,*.swf
      stat-view-servlet:
        login-username: druid
        login-password: druid
#      use-oracle-implicit-cache: true
      access-to-underlying-connection-allowed: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    database: oracle
#    database: mysql
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
#        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
server:
  port: 9101
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}::${eureka.instance.hostname}::${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    healthcheck:
      enabled: true
ribbon:
  eager-load:
    enabled: true
#logging:
#  level:
#    org.thinking.logistics.statemachine.*: DEBUG
business:
  baseUrl: http://117.184.195.185:8080/test/dep
  executor:
    corePoolSize: 10
    maxPoolSize: 200
    queueCapacity: 10
---
spring:
  profiles: dev
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5